Setup MongoDB for the GraphQL Server
DuolearnHQ/ArtPlace pull request #15
Opened 2023-05-04 08:45 UTC by RwandaGloria

- ✅Setup mongodb connection with the help of mongoose library
- ✅Use ENVs to securely store the connection URI
- ✅create a database directory under src to store the connection file

2023-05-04 13:54 UTC, pavankpdev requested changes
Please review and update the changes requested. 
In addition to that, I see a few `.js` files inside `Resolver` directory, if they are build files, please make sure not to push them.

2023-05-04 13:54 UTC, pavankpdev commented on packages/server/src/db.ts
> +export async function DB_Connect() {
The usual practice in NodeJS or JavaScript ecosystem is to use camelCase. 
Please rename the function name to `dbConnect()`

2023-05-04 13:54 UTC, pavankpdev commented on packages/server/src/db.ts
> +    // console.log(process.env.MONGO_STRING)
Remove dead code

2023-05-04 13:54 UTC, pavankpdev commented on packages/server/src/index.ts
> +            console.log("Mongo string is undefined!")
add `process.exit(1)` if mongo uri is undefined

2023-05-04 13:54 UTC, pavankpdev commented on packages/server/src/endpoints.config.ts
> +import dotenv from 'dotenv';
What is the purpose of this file?

2023-05-04 13:54 UTC, pavankpdev commented on package.json
> +    "dotenv": "^16.0.3",
Seems like the required packages are installed to root, please remove this from here and reinstall them at `packages/server`

2023-05-04 13:54 UTC, pavankpdev commented on desktop.ini
> +[ViewState]
add this file to `.gitignore`

2023-05-04 14:28 UTC, RwandaGloria commented on packages/server/src/db.ts
> +export async function DB_Connect() {
OK Got it. I will make changes to all you mentioned about.

2023-05-04 16:53 UTC, pavankpdev commented
Hey @RwandaGloria mark the reviews as resolved and let me know, once your done.

2023-05-05 08:58 UTC, pavankpdev approved these changes
Good work, merging this PR. 
Although, I might have to setup formatter and a git hooks.

2023-05-05 08:58 UTC, merged