Create token#17
DuolearnHQ/ArtPlace pull request #24
Opened 2023-05-09 16:18 UTC by ri-dev-git

Issue regarding token verification

2023-05-11 07:02 UTC, pavankpdev requested changes
Please add the types folder to `.gitignore`

2023-05-11 07:02 UTC, pavankpdev commented on packages/contracts/test/ARTP.test.ts
> +      await expect(myToken.connect(addr2).mint(addr1.address, amount)).to.be.revertedWith(`AccessControl: account 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc is missing role 0x9f2df0fed2c77648de5860a4
Seems like the test case is outdated with new Token contract modification. Please update the test cases

2023-05-11 07:02 UTC, pavankpdev commented on packages/contracts/test/ARTP.test.ts
> +    it("should not allow a non-burner to burn tokens", async function () {
Seems like the test case is outdated with new Token contract modification. Please update the test cases

2023-05-11 07:02 UTC, pavankpdev commented on packages/contracts/utils/verify.ts
Not necessary, since we have a separate script, we'll remove this, and its usage as well

2023-05-11 07:02 UTC, pavankpdev commented on packages/contracts/deploy/deployARTP.ts
The file page is invalid, this should be under `deploy/Tokens/ARTP.ts`

2023-05-11 08:11 UTC, ri-dev-git commented
hey i have made the changes please check!

2023-05-12 06:55 UTC, pavankpdev commented
Hey @ri-dev-git please the review as resolved once you complete them

2023-05-12 07:00 UTC, pavankpdev requested changes

2023-05-12 07:00 UTC, pavankpdev commented on packages/contracts/src/ARTP.sol
Hey @ri-dev-git one last change, move this file to 
`src/Token/ARTP.sol`

2023-05-12 10:35 UTC, pavankpdev approved these changes
Great Merging

2023-05-12 10:35 UTC, merged

2023-05-12 10:40 UTC, pavankpdev commented
@ri-dev-git are you on Duolearn's discord. Can you share your username?

2023-05-12 11:09 UTC, ri-dev-git commented
Nope
it's ri_dev#1118

2023-05-12 11:24 UTC, pavankpdev commented
Hey @ri-dev-git can you join the server 
[https://discord.gg/cXKMsx5h](https://discord.gg/cXKMsx5h)