Add a user context
DuolearnHQ/ArtPlace pull request #26
Opened 2023-05-11 16:32 UTC by ciradu2204

- [ ] Added a user context file under the src folder
- [ ] Created an interface to define the user object types 
- [ ] Created a UserContextType to define the types for both the user and updateUser function
- [ ] Initialized the user context 
- [ ] Created a user provider and exported it
- [ ] Created a useUser hook to access both the user and the updateUser function
- [ ] Imported the useUser hook in the index.tsx

**How to test**
- Click the login button
- View the login user name displayed

2023-05-12 06:54 UTC, pavankpdev requested changes

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/UserContext.tsx
> +    user:undefined,
Please do not init as `undefined` make it an empty object.

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/UserContext.tsx
> +    user?:USER,
Marking user as defined is not a valid, instead use a union 
`user: IUser | Record<string, string>`

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/UserContext.tsx
> +interface USER{
It is a best Practice to prefix the `interface` name with `I` example rename this interface name to `IUser`

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/UserContext.tsx
> +       //retrieve user details from db/local storage
Mark this as TODO, since this should be done later

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/pages/_app.tsx
> +import { UserProvider } from '../UserContext';
Use import alias, such as `@/context/User.tsx`

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/pages/index.tsx
> +        {!user && <button onClick={updateUser}>Click to Login</button>}
This is not necessary as we'll get a auth hook from rainbow kit

2023-05-12 06:54 UTC, pavankpdev commented on packages/frontend/src/UserContext.tsx
Please move this file to following directory. 
`context/User.tsx`

2023-05-12 13:20 UTC, ciradu2204 commented on packages/frontend/src/UserContext.tsx
> +       //retrieve user details from db/local storage
so I should update the comments and remove the implementation?

2023-05-12 13:33 UTC, ciradu2204 commented
@pavankpdev, could I add the yarn.lock in the .gitignore file?

2023-05-14 05:17 UTC, pavankpdev commented
> @pavankpdev, can I add the yarn.lock in the .gitignore file?

no please don't add that, having lock file would help us all stay in sync with package versions

2023-05-14 05:17 UTC, pavankpdev commented
let me know if all the changes are done and ready to be reviews @ciradu2204

2023-05-14 08:25 UTC, ciradu2204 commented
Yes all the changes are done
On Sun, 14 May 2023 at 07:17 Pavan Kumar ***@***.***> wrote:

> let me know if all the changes are done and ready to be reviews
> @ciradu2204 <https://github.com/ciradu2204>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DuolearnHQ/ArtPlace/pull/26#issuecomment-1546810180>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJA35MP6IXHHNWDOTQBEULDXGBTG7ANCNFSM6AAAAAAX6MA4BY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-15 04:22 UTC, pavankpdev approved these changes
Great Merging

2023-05-15 04:22 UTC, merged

2023-05-15 04:23 UTC, pavankpdev commented
@ciradu2204 can you share your discord username, and also join our server if you're not in.
[https://discord.gg/cXKMsx5h](https://discord.gg/cXKMsx5h)