Added apollo graphql with codegen
DuolearnHQ/ArtPlace pull request #27
Opened 2023-05-13 15:57 UTC by Shaju06

- [x]  Setup of apollo client with folder name gql in src.
 

- [x] Moreover added graphql codegen.

- [x] Added some gql queries aswell.

- [x] Used a public grapql server endpoint.

2023-05-14 03:14 UTC, Shaju06 commented
@pavankpdev please review

2023-05-14 05:17 UTC, pavankpdev commented
great, will review this today @Shaju06

2023-05-15 04:21 UTC, pavankpdev commented
@devnm21 can you review this

2023-05-15 08:06 UTC, Shaju06 commented
@pavankpdev just resolved it

2023-05-16 14:59 UTC, pavankpdev requested changes
Hey @Shaju06 a few minor changes, please have a look

2023-05-16 14:59 UTC, pavankpdev commented on packages/frontend/src/gql/codegen.ts
> +  schema: 'https://rickandmortyapi.com/graphql', // Replace it with your GraphQL server endpoint
Let's have this config in ENV

2023-05-16 14:59 UTC, pavankpdev commented on packages/frontend/src/gql/index.ts
> +  uri: 'https://rickandmortyapi.com/graphql', // Replace with your GraphQL API endpoint
Let's have this config in ENV

2023-05-16 15:53 UTC, Shaju06 commented
@pavankpdev  Added NEXT_PUBLIC_GRAPHQL_SERVER_ENDPOINT for graphql endpoint

2023-05-16 16:44 UTC, pavankpdev commented
Hey @Shaju06 looks like the ENV you used, wasn't added to `.example.env`, can you please do, if the `.example.env` doesn't exist please create one. 

This would help others developers who will be syncing up with your changes.

2023-05-16 17:37 UTC, pavankpdev approved these changes
Great, merging

2023-05-16 17:37 UTC, pavankpdev approved these changes
Great, merging

2023-05-16 17:37 UTC, merged

2023-05-16 17:38 UTC, pavankpdev commented
@Shaju06 can you share your Discord username and if you're not in Duolearn server, please join here [https://discord.gg/nkF2SyKw](https://discord.gg/nkF2SyKw)