Login page#4
DuolearnHQ/ArtPlace pull request #31
Opened 2023-05-22 12:06 UTC by ri-dev-git

Made the changes as asked in the review!

2023-05-24 08:31 UTC, pavankpdev commented
Great, I'll have a look

2023-05-28 09:12 UTC, ri-dev-git commented
Hi @pavankpdev! How does it look?

2023-05-29 08:50 UTC, pavankpdev commented
Hey @ri-dev-git checking this now

2023-05-29 09:15 UTC, pavankpdev commented
Hey @ri-dev-git, it appears that there are some UI issues that need attention. Here's a rundown:

1. We have a responsiveness issue, which you can check out [here](http://responsivetesttool.com/?url=http://localhost:3000/auth/login).
2. Please ensure that the images have the correct border radius and gap as per the Figma designs.
3. The button size seems larger than necessary, and the font size remains unchanged. This can impact the user experience and accessibility.

Additionally, for tasks like signing a message, please avoid using unnecessary libraries. We already have Rainbow Kit and Wagmi installed in the project, so let's utilize them for these tasks.

Please address these issues promptly. Thank you!

2023-05-29 09:24 UTC, pavankpdev requested changes

2023-05-29 09:24 UTC, pavankpdev commented on Lock/deploy.ts
Delete this file

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/.env.example
Why do we have another example env? please delete the other one

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/api/auth/[...nextauth].ts
> +          const siwe = new SiweMessage(JSON.parse(credentials?.message || "{}"))
Let's utilize ethers.js or wagmi for decoding and verifying the signature, and remove the `siwe` library.

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +    winSize<=912?
Please consult the Chakra documentation for guidance on creating responsive pages as the current approach is not recommended.

[Check here](https://chakra-ui.com/docs/styled-system/responsive-styles)

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +    <Box display="flex" direction="row" w="100%" height="100%" alignItems="center" justifyContent="center">
It is advised to avoid excessive use of divs and block elements. Instead, consider utilizing heading tags when appropriate.

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +        // can remove all 'authenticationStatus' checks
No need of auth check here, we'll use a middleware for that, please remove this

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +                    Wrong network
Display a switch network button, instead of wrong network

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +        height:"100%",
Do not edit global styles, unless required, please share the purpose of adding global styles.

2023-05-29 09:24 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +import nft1 from "../../../assets/Rectangle 3784.png"
Use path alias

2023-05-29 09:51 UTC, ri-dev-git commented on packages/frontend/src/pages/api/auth/[...nextauth].ts
> +          const siwe = new SiweMessage(JSON.parse(credentials?.message || "{}"))
https://www.rainbowkit.com/docs/authentication it suggested using siwe. Do you still want me to use ethers/wagmi?

2023-05-29 13:08 UTC, ri-dev-git commented on packages/frontend/src/theme/index.ts
> +        height:"100%",
i have used the global styling because the global identifier did not inherit  the 100% of the screen!

2023-05-29 15:58 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +        height:"100%",
You can use `heigh={'100vh'}` for the root element.

2023-05-29 15:58 UTC, pavankpdev commented on packages/frontend/src/pages/api/auth/[...nextauth].ts
> +          const siwe = new SiweMessage(JSON.parse(credentials?.message || "{}"))
yeah let's stick with etherjs/wagmi

2023-06-02 15:19 UTC, pavankpdev commented
Hey @ri-dev-git I see some fixes, is this still WIP or ready to be reviewed?

2023-06-02 15:22 UTC, ri-dev-git commented
> Hey @ri-dev-git I see some fixes, is this still WIP or ready to be reviewed? 

Can you tell me  about the fixes more? I have pushed it for review only

2023-06-02 15:40 UTC, pavankpdev commented
Oh okay, I meant that I saw a few commits and asked you whether if it's ready to be reviewed

2023-06-03 15:14 UTC, pavankpdev commented
Hey @ri-dev-git couple of things are pending, and refactoring is required, here's [explanation video of mine](https://www.loom.com/share/31a61b59a3ef4d81bc833cc5962a1efa)

2023-06-03 15:23 UTC, pavankpdev requested changes

2023-06-03 15:23 UTC, pavankpdev commented on Lock/deploy.ts
Seems like a duplicate file delete this

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/pages/api/auth/[...nextauth].ts
> +    // CredentialsProvider({
Remove commented code, they increase the bundle size

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/pages/api/auth/[...nextauth].ts
> +          const { address, privateKey } = credentials;
This would done on the backend, let's remove this auth handler

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +        <Flex magin="0" padding="0" direction="column" alignItems="center" justifyContent="center" background= "linear-gradient(180deg, #F461A7 0%, #6D0034 100%)"display={{ base: "none", lg: "block"
Seems like the image grid is being implemented using Flex, and I see a lot of hardcoded heights. Use CSS Grid instead

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +              <Image src={nft1} alt="nft1" width={396.21} height={396.21}  />
Hardcoded image size, this is a bad practice, wrap the images inside a block element such as <Box/> and provide dynamic width and height and also `relative` position, and use `fill` property in `Image`

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/pages/auth/login.tsx
> +              <Text size={["","","","18px","14px","20px"]} w={["","","","80%","70%"]} fontWeight="400" lineHeight="30px" >
Do not use array to define responsiveness use object example
```TS
{
  base: "12px",
  sm: "13px"
}
```

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +        height:"100%"
redundant, height is always `100%`, remove this

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +      html:{
do not assign style to `html` remove this

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +      "[data-rk]":{
Seems like another root style, remove this

2023-06-03 15:23 UTC, pavankpdev commented on packages/frontend/src/theme/index.ts
> +      "#__next":{
`100vh` should be defined to the root element of the certain page not to the root element of the project, defining to `#__next` would lead to style changes in all the pages throughout the project, remove this. 

Use a `<Box />` in the login page and assign `100vh` to that.

2023-06-08 09:42 UTC, pavankpdev commented
@ri-dev-git any update on this PR?

2023-06-08 09:44 UTC, ri-dev-git commented
> @ri-dev-git any update on this PR?

yes! i am working on it! Been busy these days, will Hit you up once done

2023-06-09 09:03 UTC, ri-dev-git commented
Hey @pavankpdev! it looks like i wont be able to work on this can you please assign this to someone else?

2023-06-09 09:03 UTC, closed without merging

2023-06-10 09:09 UTC, ri-dev-git commented on packages/frontend/src/theme/index.ts
> +      "[data-rk]":{
Hi @pavankpdev! removing this and `#next` miss-aligns the screen! you can try by testing it locally! if it has some solution please lmk :)