Register page
DuolearnHQ/ArtPlace pull request #32
Opened 2023-05-31 08:55 UTC by Harshalyadav

Solve  merge conflict

2023-06-02 14:35 UTC, Harshalyadav commented
@pavankpdev are you check my PR?

2023-06-02 15:19 UTC, pavankpdev commented
Hey @Harshalyadav apologies, I was away, I'll check your PR tomorrow.

2023-06-03 14:54 UTC, pavankpdev commented
Hey @Harshalyadav I went through the PR, seems like the UI isn't aligned properly, [watch this video](https://www.loom.com/share/a8f9c111709d4d44ae3eb264f42b6490), I've explained the issues

2023-06-03 14:59 UTC, pavankpdev requested changes

2023-06-03 14:59 UTC, pavankpdev commented on packages/frontend/public/registerAssist/Men.png
Do not add images to public directory, add them to `src/assets`

2023-06-03 14:59 UTC, pavankpdev commented on packages/frontend/src/pages/_app.tsx
Seems like you didn't take a pull from my update, please do it, I've pushed a rainbow kit setup.

2023-06-03 14:59 UTC, pavankpdev commented on packages/frontend/src/pages/auth/register.tsx
With over 500 lines of code for a single page, it seems there is room for improvement. It is advisable to carefully examine the code and consider refactoring to ensure better practices and identify any underlying issues.

2023-06-03 14:59 UTC, pavankpdev commented on packages/frontend/src/pages/index.tsx
`pages/index.tsx` is a different route, let's not render register page here

2023-06-04 07:47 UTC, Harshalyadav commented on packages/frontend/public/registerAssist/Men.png
ok

2023-06-07 07:49 UTC, Harshalyadav commented
@pavankpdev for validating, could I use Formik, regex or you have other concept.

2023-06-08 09:41 UTC, pavankpdev commented
> @pavankpdev for validating, could I use Formik, regex or do you have another concept?. will tablet devices show form part only?

@Harshalyadav use can use [zod](https://zod.dev/) for form validation, tablet devices will only show the forms

2023-06-13 10:43 UTC, Harshalyadav commented
@pavankpdev please check the validation. I need your help, where I put rainbowkit wallet custom button.

2023-06-15 08:34 UTC, Harshalyadav commented
@pavankpdev did you check my PR?

2023-06-16 19:36 UTC, pavankpdev commented
not yet, @Harshalyadav I'll do it tonight this sunday

2023-07-15 05:57 UTC, merged